language: elixir
elixir:
  - '1.11.1'
otp_release:
  - '21.0'

services: 
  - docker
    
before_install:
  - docker build -t lucasboisbourdin/timemanager_phoenix .

after_success: 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_LOGIN" --password-stdin
  - docker push lucasboisbourdin/timemanager_phoenix

deploy: 
  provider: elasticbeanstalk
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
  region: eu-west-3
  app: docker-timemanager
  env: DockerTimemanager-env
  bucket_name: elasticbeanstalk-eu-west-3-840193320740
  bucket_path: docker-timemanager
  on:
    branch: main
  skip_cleanup: false