language: elixir
elixir:
  - '1.11.1'
otp_release:
  - '21.0'

services: 
  - docker
    
before_install:
  - docker build -t lucasboisbourdin/timemanager_phoenix .

after_success: 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_LOGIN" --password-stdin
  - docker push lucasboisbourdin/timemanager_phoenix