language: elixir
elixir:
  - '1.11.1'
otp_release:
  - '21.0'

services: 
  - docker
    
before_install:
  - docker-compose build

after_success: 
  - docker tag piscine_epitech_phoenix lucasboisbourdin/timemanager_phoenix
  - docker tag piscine_epitech_vuejs lucasboisbourdin/timemanager_vuejs
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_LOGIN" --password-stdin
  - docker push lucasboisbourdin/timemanager_phoenix
  - docker push lucasboisbourdin/timemanager_vuejs

addons:
  ssh_known_hosts: <deploy-host>

before_deploy:
- openssl aes-256-cbc -K $encrypted_<...>_key -iv $encrypted_<...>_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: sudo mkdir travis
  on:
    branch: main