version: '3'

services:
  vuejs:
    build:
      context: ./Front_TimeMachine_2020
    #image: lucasboisbourdin/timemanager_phoenix
    command: /bin/bash -c 'npm run serve'
    ports:
      - "8080:8080"
    depends_on:
      - phoenix

  phoenix:
    build:
      context: .
    #image: lucasboisbourdin/timemanager_phoenix
    command: /bin/bash -c 'mix ecto.reset && mix phx.server'
    environment:
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: timemanager_database
      PGPORT: 5432
      PGHOST: db
    ports:
      - "4001:4001"
    depends_on:
      - db

  db:
    image: postgres:13.0
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: