language: elixir
elixir:
  - '1.11.1'
otp_release:
  - '22.0'

sudo: required

services: 
  - docker
    
before_install:
  - docker build -t lucasboisbourdin/hello .

after_success: 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_LOGIN" --password-stdin
  - docker push lucasboisbourdin/hello